# Generated by Django 5.2.1 on 2025-06-09 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usernote'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernote',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
