# Generated by Django 5.2.1 on 2025-06-14 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_options_userupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userupload',
            old_name='filename',
            new_name='file_name',
        ),
        migrations.RenameField(
            model_name='userupload',
            old_name='filepath',
            new_name='file_path',
        ),
    ]
