# Generated by Django 5.2.1 on 2025-06-14 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_rename_filename_userupload_file_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userupload",
            name="date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
