# Generated by Django 5.2.1 on 2025-06-14 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userupload_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userupload',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='userupload',
            name='type',
        ),
        migrations.CreateModel(
            name='UploadMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('name', 'Name'), ('type', 'Type'), ('size', 'Size'), ('pages', 'Pages')])),
                ('value', models.CharField()),
                ('user_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userupload')),
            ],
        ),
    ]
