# Generated by Django 5.2.1 on 2025-06-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_remove_userupload_file_name_remove_userupload_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadmetadata",
            name="name",
            field=models.CharField(
                choices=[
                    ("name", "Name"),
                    ("extension", "Extension"),
                    ("size", "Size"),
                    ("pages", "Pages"),
                    ("content_type", "ContentType"),
                ]
            ),
        ),
    ]
