# Generated by Django 5.2.1 on 2025-06-16 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configuration", "0004_semester_previous_studyyear_previous"),
        ("users", "0009_alter_uploadmetadata_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="semester",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="configuration.semester",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="study_year",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="configuration.studyyear",
            ),
        ),
    ]
