# Generated by Django 5.2.1 on 2025-06-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configuration", "0002_alter_resource_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="banner",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
