# Generated by Django 5.2.1 on 2025-06-14 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_alter_resource_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='configuration.semester'),
        ),
        migrations.AddField(
            model_name='studyyear',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='configuration.studyyear'),
        ),
    ]
