# Generated by Django 5.2.3 on 2025-07-26 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_semester_previous_studyyear_previous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='order',
        ),
        migrations.RemoveField(
            model_name='studyyear',
            name='order',
        ),
    ]
