# Generated by Django 5.2.1 on 2025-06-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_courseregisteredstudent_student_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregisteredstudent',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
