# Generated by Django 5.2.1 on 2025-06-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_alter_comments_options_courseuploadfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="askedcourse",
            name="approved_date",
            field=models.DateTimeField(default=None),
        ),
    ]
