# Generated by Django 5.2.3 on 2025-06-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0009_rename_comments_comment_alter_comment_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
